# Generated by Django 2.2.5 on 2019-09-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studenci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miasto',
            old_name='miasto',
            new_name='nazwa',
        ),
    ]
